default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: househunter_development

test:
  <<: *default
  database: househunter_test

production:
  <<: *default
  database: househunter_production
  username: househunter
  password: <%= ENV['HOUSEHUNTER_DATABASE_PASSWORD'] %>
